package com.adaptive.companion.ui

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

val LocalUiLanguage = staticCompositionLocalOf { "zh-CN" }

/** Translate UI only; original conversation and diagnostic data are kept intact. */
object UiStrings {
    val languages = listOf("zh-CN", "zh-TW", "ja", "en-US")
    val labels = listOf("简体中文", "繁體中文", "日本語", "English (US)")
    val catalog: Map<String, List<String>> = mapOf(
        "OpenWoven" to listOf("OpenWoven", "OpenWoven", "OpenWoven", "OpenWoven"),
        "Add image" to listOf("＋图片", "＋圖片", "＋画像", "+ Image"),
        "At most four images per turn" to listOf("一轮最多4张图片，请等上一轮回复后再发，或删除待回复图片", "一輪最多4張圖片，請等上一輪回覆後再傳，或刪除待回覆圖片", "1ターンは画像4枚までです。返信を待つか、保留中の画像を削除してください", "At most 4 images per turn. Wait for the reply or delete a pending image"),
        "Remove image" to listOf("移除", "移除", "削除", "Remove"),
        "Chat action failed" to listOf("这次操作未完成，可重试或查看设置", "這次操作未完成，可重試或查看設定", "操作を完了できませんでした。再試行するか設定を確認してください", "This action could not be completed. Retry or check settings"),
        "Reply again" to listOf("重新回复", "重新回覆", "もう一度返信", "Reply again"),
        "Selected image" to listOf("已选图片", "已選圖片", "選択した画像", "Selected image"),
        "Image upload notice" to listOf("发送后交给当前模型；图片可能额外计费", "傳送後交給目前模型；圖片可能額外計費", "送信すると現在のモデルへ渡され、画像料金がかかる場合があります", "Sent to your selected model; images may cost extra"),
        "Image could not be opened" to listOf("无法读取图片，请选择有效图片（原图最多20MB）", "無法讀取圖片，請選有效圖片（原圖最多20MB）", "画像を読み込めません。有効な画像（最大20MB）を選んでください", "Cannot open image. Select a valid image up to 20 MB"),
        "Selected model does not support images" to listOf("请先配置接口并勾选当前模型可看图", "請先設定介面並勾選目前模型可看圖", "接続を設定し、現在のモデルの画像対応を有効にしてください", "Configure your provider and enable vision for the selected model"),
        "Waiting for draft" to listOf("输入框还有内容，等你发完再回复", "輸入框還有內容，等你傳完再回覆", "入力中です。送信が終わるまで返信を待ちます", "Waiting until your draft is sent or cleared"),
        "Waiting for turn" to listOf("等你说完：停止输入约{0}秒后回复", "等你說完：停止輸入約{0}秒後回覆", "入力が止まって約{0}秒後に返信します", "Waiting for your turn to finish: about {0}s after typing stops"),
        "Turn wait seconds" to listOf("说完再回复：{0}秒", "說完再回覆：{0}秒", "入力終了後の待ち時間：{0}秒", "Turn wait: {0} seconds"),
        "Turn wait help" to listOf("默认20秒，可调10–60秒。连续发送合并理解；输入框有文字或正在拼字时暂停。只看本应用输入状态，不读取其他应用的键盘。", "預設20秒，可調10–60秒。連續傳送一起理解；輸入框有文字或組字時暫停。只看本應用輸入狀態。", "初期値20秒、10〜60秒。連続送信をまとめて理解し、下書き・変換中は待ちます。他のアプリの入力は読みません。", "Default 20s (10–60). Sent bubbles form one turn; drafts and IME composition pause replies. Only this app's composer is observed."),
        "Daily reply length" to listOf("日常回复长短", "日常回覆長短", "日常の返信の長さ", "Daily reply length"),
        "Daily length help" to listOf("左0：简短；右1：详细。默认0.30，轻松少啰嗦。仅日常聊天生效，不截断你要求的文章或代码。", "左0：簡短；右1：詳細。預設0.30，輕鬆少囉嗦。僅日常聊天，不截斷文章或程式碼。", "左0：短く、右1：詳しく。初期値0.30。日常会話のみで、文章やコードは対象外です。", "Left 0: brief; right 1: detailed. Default 0.30. Casual chat only; requested documents and code stay intact."),
        "Time zone" to listOf("聊天时区（留空跟随手机）", "聊天時區（留空跟隨手機）", "会話のタイムゾーン（空欄で端末に追従）", "Chat time zone (blank follows device)"),
        "Time zone help" to listOf("默认留空。可填Asia/Shanghai、Asia/Hong_Kong等标准时区；每次回复前读取当前时间。不改变原始消息时间或记忆归档。", "預設留空。可填Asia/Shanghai、Asia/Hong_Kong等時區；每次回覆前讀取目前時間。不改原始時間或記憶歸檔。", "空欄が初期値です。Asia/Tokyoなどを指定でき、返信前に現在時刻を取得します。記録やアーカイブ時刻は変更しません。", "Blank by default. Use zone IDs such as Asia/Shanghai; time is refreshed before replies. Original timestamps and archives are unchanged."),
        "Save conversation settings" to listOf("保存聊天设置", "儲存聊天設定", "会話設定を保存", "Save conversation settings"),
        "Settings" to listOf("设置", "設定", "設定", "Settings"),
        "AI companion" to listOf("AI陪伴", "AI陪伴", "AIコンパニオン", "AI companion"),
        "Message…" to listOf("输入消息…", "輸入訊息…", "メッセージを入力…", "Message…"),
        "Send" to listOf("发送", "傳送", "送信", "Send"),
        "Preparing a reply…" to listOf("正在准备回复…", "正在準備回覆…", "返信を準備中…", "Preparing a reply…"),
        "Retry" to listOf("重试", "重試", "再試行", "Retry"),
        "Message" to listOf("消息", "訊息", "メッセージ", "Message"),
        "Copy" to listOf("复制", "複製", "コピー", "Copy"),
        "Delete" to listOf("删除", "刪除", "削除", "Delete"),
        "Regenerate" to listOf("重新生成", "重新產生", "再生成", "Regenerate"),
        "Feedback" to listOf("反馈", "回饋", "フィードバック", "Feedback"),
        "👍 Good" to listOf("👍 挺好", "👍 不錯", "👍 よかった", "👍 Good"),
        "Too long" to listOf("太长", "太長", "長すぎる", "Too long"),
        "Too short" to listOf("太短", "太短", "短すぎる", "Too short"),
        "Too many questions" to listOf("反问太多", "反問太多", "質問が多すぎる", "Too many questions"),
        "Too cold" to listOf("太冷淡", "太冷淡", "そっけなさすぎる", "Too cold"),
        "Too verbose" to listOf("太啰嗦", "太囉嗦", "くどすぎる", "Too verbose"),
        "Too serious" to listOf("太严肃", "太嚴肅", "堅すぎる", "Too serious"),
        "Too playful" to listOf("玩笑太多", "玩笑太多", "冗談が多すぎる", "Too playful"),
        "Too proactive" to listOf("太主动", "太主動", "積極的すぎる", "Too proactive"),
        "Be more proactive" to listOf("再主动一点", "再主動一點", "もう少し積極的に", "Be more proactive"),
        "How did that conversation feel?" to listOf("刚才的交流感觉怎样？", "剛才的交流感覺如何？", "今の会話はどうでしたか？", "How did that conversation feel?"),
        "Naturalness {0} / 5" to listOf("自然程度 {0}/5", "自然程度 {0}/5", "自然さ {0}/5", "Naturalness {0} / 5"),
        "Comfort {0} / 5" to listOf("舒适程度 {0}/5", "舒適程度 {0}/5", "心地よさ {0}/5", "Comfort {0} / 5"),
        "Reply length" to listOf("回复长短", "回覆長短", "返信の長さ", "Reply length"),
        "Initiative" to listOf("主动程度", "主動程度", "積極性", "Initiative"),
        "Short" to listOf("短", "短", "短い", "Short"),
        "Good" to listOf("适中", "適中", "ちょうどよい", "Good"),
        "Long" to listOf("长", "長", "長い", "Long"),
        "Low" to listOf("低", "低", "低い", "Low"),
        "High" to listOf("高", "高", "高い", "High"),
        "Skip" to listOf("跳过", "略過", "スキップ", "Skip"),
        "Sending" to listOf("发送中", "傳送中", "送信中", "Sending"),
        "Failed" to listOf("失败", "失敗", "失敗", "Failed"),
        "Waiting reply" to listOf("稍后回复（后台可能延后）", "稍後回覆（背景可能延後）", "後ほど返信（バックグラウンドでは遅れる場合があります）", "Waiting reply"),
        "Conversation" to listOf("对话", "對話", "会話", "Conversation"),
        "Humanized reply timing" to listOf("自然回复节奏", "自然回覆節奏", "自然な返信タイミング", "Humanized reply timing"),
        "Reply timing help" to listOf("分条逐条出现：短句间约1秒，较长约2秒，默认最长2.5秒。关闭后仍分条，但立即显示；不会额外调用模型。", "分條逐條出現：短句間約1秒，較長約2秒，預設最長2.5秒。關閉後仍分條，但立即顯示；不會額外呼叫模型。", "短文は約1秒、長めの文は約2秒の間隔で順番に表示します。初期上限は2.5秒。オフでも吹き出しは分けますが即時表示。追加API呼び出しはありません。", "Show bubbles one at a time: about 1 second for short messages, 2 for longer ones, capped at 2.5 by default. Off keeps separate bubbles but shows them immediately. No extra model calls."),
        "Greeting delay" to listOf("开场白稍后回复（目标1–3分钟）", "開場白稍後回覆（目標1–3分鐘）", "短い呼びかけへの返信を遅らせる（目安1～3分）", "Greeting delay"),
        "Greeting help" to listOf("默认关闭。开启后，独立‘在吗’可多等1–3分钟；继续发实际内容就恢复普通等待。", "預設關閉。開啟後，獨立『在嗎』可多等1–3分鐘；繼續傳實際內容就恢復一般等待。", "初期設定はオフ。オンの場合、短い呼びかけを1〜3分遅らせます。内容を続けて送ると通常の待ち時間に戻ります。", "Off by default. When enabled, standalone greetings wait 1–3 minutes; further sent content restores the normal wait."),
        "Build or update my AUL" to listOf("补充资料与角色问卷（10/50题）", "補充資料與角色問卷（10/50題）", "プロフィール・役柄の質問（10/50問）", "Update profile and character interview (10/50)"),
        "Memory calendar" to listOf("记忆日历", "記憶日曆", "記憶カレンダー", "Memory calendar"),
        "Calendar subtitle" to listOf("日／周／月归档，查找过去的聊天", "日／週／月歸檔，尋找過去的聊天", "日・週・月の記録と過去の会話検索", "Day/week/month archives and past conversations"),
        "Notifications" to listOf("通知", "通知", "通知", "Notifications"),
        "Sound" to listOf("声音", "聲音", "音", "Sound"),
        "Vibration" to listOf("振动", "震動", "振動", "Vibration"),
        "Proactive messages" to listOf("主动关心", "主動關心", "こちらからの声かけ", "Proactive messages"),
        "Quiet hours" to listOf("免打扰时段", "勿擾時段", "通知を控える時間帯", "Quiet hours"),
        "Background" to listOf("后台运行", "背景執行", "バックグラウンド動作", "Background"),
        "Resident mode" to listOf("常驻后台", "常駐背景", "常駐モード", "Resident mode"),
        "Resident help" to listOf("关闭后使用省电调度。常驻会显示持续通知并额外耗电，仍可能被系统停止，不保证准点。", "關閉後使用省電排程。常駐會顯示持續通知並額外耗電，仍可能被系統停止，不保證準時。", "オフにすると省電力スケジュールを使います。常駐は通知を表示し電力を消費しますが、停止・遅延の可能性は残ります。", "Off uses battery-friendly scheduling. Resident mode shows an ongoing notification and uses more power; Android can still stop or delay it."),
        "Google push (FCM)" to listOf("Google推送（FCM）", "Google推播（FCM）", "Googleプッシュ通知（FCM）", "Google push (FCM)"),
        "FCM unavailable" to listOf("尚未接入：需要Firebase项目和服务端", "尚未接入：需要Firebase專案與伺服器", "未接続：Firebaseプロジェクトとサーバーが必要", "Not connected: requires a Firebase project and server"),
        "Enable resident mode?" to listOf("启用可停止的常驻模式？", "啟用可停止的常駐模式？", "停止可能な常駐モードを有効にしますか？", "Enable resident mode?"),
        "Resident confirmation" to listOf("会持续显示通知并等待已保存的待办。不是防杀保活，也不保证准点；设置和通知都能停止。", "會持續顯示通知並等待已儲存的待辦。不是防止系統終止，也不保證準時；設定與通知均可停止。", "保存済みの予定を待ちながら継続通知を表示します。停止防止や定刻実行は保証されません。設定・通知から停止できます。", "Shows an ongoing notification while waiting for saved jobs. Not kill-proof or exact-time delivery; stop it in settings or the notification."),
        "Enable" to listOf("启用", "啟用", "有効にする", "Enable"),
        "Cancel" to listOf("取消", "取消", "キャンセル", "Cancel"),
        "Why no Google push yet?" to listOf("为什么还没有Google推送？", "為什麼還沒有Google推播？", "Googleプッシュ通知が未接続なのはなぜ？", "Why no Google push yet?"),
        "FCM explanation" to listOf("FCM只是投递通道。记忆、计时和AI回复需要服务端、鉴权与同步。当前先提供本地省电／常驻模式，不自动检测Google服务。", "FCM只是投遞通道。記憶、計時與AI回覆需要伺服器、驗證與同步。目前先提供本地省電／常駐模式，不自動偵測Google服務。", "FCMは配送経路です。記憶・予約・AI返信にはサーバー、認証、同期が必要です。現在は端末内の省電力／常駐モードを提供し、Googleサービスの自動検出はしません。", "FCM is a delivery channel. Memory, scheduling and AI replies need a server, authentication and synchronization. This version offers local system/resident modes, without detecting Google services."),
        "OK" to listOf("明白", "了解", "了解", "OK"),
        "Developer" to listOf("开发者", "開發者", "開発者", "Developer"),
        "Administrator" to listOf("管理员", "管理員", "管理者", "Administrator"),
        "Provider and models" to listOf("接口与模型", "介面與模型", "接続先とモデル", "Provider and models"),
        "AUL inspector" to listOf("用户画像查看", "使用者畫像檢視", "ユーザー情報の確認", "AUL inspector"),
        "Profile, state and preferences" to listOf("画像、状态和交流偏好", "畫像、狀態與交流偏好", "人物情報・状態・会話の好み", "Profile, state and preferences"),
        "Memory and audit" to listOf("记忆与审计", "記憶與稽核", "記憶と変更記録", "Memory and audit"),
        "Raw, Evidence, summaries, policy" to listOf("原话、证据、摘要与策略", "原話、證據、摘要與策略", "原文・根拠・要約・方針", "Raw, Evidence, summaries, policy"),
        "Scheduler debug" to listOf("待办调试", "排程除錯", "予定のデバッグ", "Scheduler debug"),
        "Pending, sent, cancelled, expired" to listOf("等待、已发、取消与过期", "等待、已發、取消與過期", "待機・送信済み・キャンセル・期限切れ", "Pending, sent, cancelled, expired"),
        "Core and timing" to listOf("核心与节奏参数", "核心與節奏參數", "コアとタイミング", "Core and timing"),
        "Budgets, thresholds and delivery" to listOf("预算、阈值与发送节奏", "預算、門檻與傳送節奏", "予算・しきい値・返信タイミング", "Budgets, thresholds and delivery"),
        "App" to listOf("应用", "應用程式", "アプリ", "App"),
        "Dark theme" to listOf("深色模式", "深色模式", "ダークモード", "Dark theme"),
        "Clear chat" to listOf("清空对话", "清空對話", "会話を消去", "Clear chat"),
        "Deletes local chat, memory and learned profile" to listOf("删除本地聊天、记忆和已学习画像", "刪除本地聊天、記憶與已學習畫像", "端末内の会話・記憶・学習した情報を削除", "Deletes local chat, memory and learned profile"),
        "About" to listOf("关于AI", "關於AI", "AIについて", "About"),
        "AI identity and version" to listOf("AI身份与版本", "AI身分與版本", "AIの説明とバージョン", "AI identity and version"),
        "Clear all companion data?" to listOf("清空聊天和已学习数据？", "清空聊天與已學習資料？", "会話と学習した情報を消去しますか？", "Clear chat and learned data?"),
        "Chat, memory, scheduled messages and learned preferences will be deleted. Provider and app settings are kept." to listOf("本地聊天、记忆、待办和已学习画像会被删除，无法撤销；接口、语言、AI昵称和角色设置保留。", "本機聊天、記憶、排程與已學習畫像會刪除且無法復原；介面、語言、AI暱稱與角色設定保留。", "端末内の会話・記憶・予定・学習した情報を削除し、元に戻せません。接続先・言語・AIの呼び名・役柄設定は残ります。", "Local chat, memory, schedules and learned profile will be deleted irreversibly. Provider, language, AI nickname and character settings are kept."),
        "Clear" to listOf("清空", "清空", "消去", "Clear"),
        "OpenWoven is an AI system, not a human. It can remember information you share and adapt its conversation style. Natural delivery timing does not represent a real person typing." to listOf("OpenWoven是AI系统，不是真人。它会记住你分享的信息并调整交流方式；自然回复节奏不代表真人正在输入。", "OpenWoven是AI系統，不是真人。它會記住你分享的資訊並調整交流方式；自然回覆節奏不代表真人正在輸入。", "OpenWovenはAIであり人間ではありません。共有された情報を記憶し会話を調整します。返信タイミングは人間の入力を示すものではありません。", "OpenWoven is an AI system, not a human. It can remember information you share and adapt its conversation style. Natural delivery timing does not represent a real person typing."),
        "Your conversation database stays in this app's private storage unless your configured AI provider receives a prompt." to listOf("数据库保存在应用私有空间；生成回复时，必要上下文会发给你配置的模型服务。", "資料庫儲存在應用程式私有空間；產生回覆時，必要上下文會傳給你設定的模型服務。", "データベースはアプリ専用領域に保存されます。返信時に必要な文脈は設定したモデルサービスへ送られます。", "Your conversation database stays in this app's private storage unless your configured AI provider receives a prompt."),
        "Version {0}" to listOf("版本 {0}", "版本 {0}", "バージョン {0}", "Version {0}"),
        "Administrator access" to listOf("管理员入口", "管理員入口", "管理者アクセス", "Administrator access"),
        "Password" to listOf("密码", "密碼", "パスワード", "Password"),
        "Incorrect password" to listOf("密码不正确", "密碼不正確", "パスワードが違います", "Incorrect password"),
        "Password verification failed" to listOf("密码验证失败", "密碼驗證失敗", "パスワード確認に失敗しました", "Password verification failed"),
        "Checking…" to listOf("检查中…", "檢查中…", "確認中…", "Checking…"),
        "Unlock" to listOf("解锁", "解鎖", "解除", "Unlock"),
        "Provider" to listOf("接口与模型", "介面與模型", "接続先とモデル", "Provider"),
        "Base URL" to listOf("接口地址（Base URL）", "介面位址（Base URL）", "接続先URL（Base URL）", "Base URL"),
        "API key" to listOf("API密钥", "API金鑰", "APIキー", "API key"),
        "Dialogue model" to listOf("当前对话模型", "目前對話模型", "現在の会話モデル", "Dialogue model"),
        "Observer model" to listOf("语义观察模型", "語意觀察模型", "意味解析用モデル", "Observer model"),
        "Memory summaries use the local deterministic pipeline (no additional model call)." to listOf("记忆摘要本地整理，不额外调用模型。", "記憶摘要在本地整理，不額外呼叫模型。", "記憶の要約は端末内で整理し、追加のモデル呼び出しはしません。", "Memory summaries use the local deterministic pipeline (no additional model call)."),
        "Temperature" to listOf("随机程度（Temperature）", "隨機程度（Temperature）", "生成の変化（Temperature）", "Temperature"),
        "Top P" to listOf("候选范围（Top P）", "候選範圍（Top P）", "候補範囲（Top P）", "Top P"),
        "Max tokens" to listOf("最大输出token", "最大輸出token", "最大出力トークン", "Max tokens"),
        "Timeout seconds" to listOf("超时秒数", "逾時秒數", "タイムアウト（秒）", "Timeout seconds"),
        "Semantic Observer" to listOf("语义观察（额外模型调用）", "語意觀察（額外模型呼叫）", "意味解析（追加モデル呼び出し）", "Semantic Observer"),
        "Learning enabled" to listOf("开启偏好学习", "啟用偏好學習", "好みの学習を有効にする", "Learning enabled"),
        "Save" to listOf("保存", "儲存", "保存", "Save"),
        "Test connection" to listOf("测试连接", "測試連線", "接続テスト", "Test connection"),
        "Reset" to listOf("恢复参数默认值", "還原參數預設值", "パラメータを初期値に戻す", "Reset"),
        "Stable profile" to listOf("稳定画像", "穩定畫像", "安定した人物情報", "Stable profile"),
        "Current state" to listOf("当前状态", "目前狀態", "現在の状態", "Current state"),
        "Relationship" to listOf("相处历史", "相處歷史", "関係の履歴", "Relationship"),
        "Interaction preferences" to listOf("交流偏好", "交流偏好", "会話の好み", "Interaction preferences"),
        "Scheduled messages" to listOf("已保存的待办", "已儲存的排程", "保存済みの予定", "Scheduled messages"),
        "Run now" to listOf("立即执行", "立即執行", "今すぐ実行", "Run now"),
        "No scheduled messages" to listOf("暂无待办", "暫無排程", "予定はありません", "No scheduled messages"),
        "Memory" to listOf("记忆", "記憶", "記憶", "Memory"),
        "Context budget" to listOf("上下文预算", "上下文預算", "文脈の予算", "Context budget"),
        "Summary message threshold" to listOf("滚动摘要消息阈值", "滾動摘要訊息門檻", "会話要約のメッセージ数", "Summary message threshold"),
        "Summary token threshold" to listOf("滚动摘要token阈值", "滾動摘要token門檻", "会話要約のトークン数", "Summary token threshold"),
        "Learning" to listOf("学习速度", "學習速度", "学習の速さ", "Learning"),
        "Weak evidence rate" to listOf("弱信号调整速度", "弱訊號調整速度", "弱い手がかりでの調整速度", "Weak evidence rate"),
        "Explicit evidence rate" to listOf("明确表达调整速度", "明確表達調整速度", "明確な希望での調整速度", "Explicit evidence rate"),
        "Correction evidence rate" to listOf("纠正反馈调整速度", "糾正回饋調整速度", "訂正による調整速度", "Correction evidence rate"),
        "Maximum per day" to listOf("每日最多主动消息", "每日最多主動訊息", "1日の声かけ上限", "Maximum per day"),
        "Minimum interval hours" to listOf("主动消息最小间隔（小时）", "主動訊息最小間隔（小時）", "声かけの最短間隔（時間）", "Minimum interval hours"),
        "Quiet starts" to listOf("免打扰开始小时", "勿擾開始時刻", "通知を控え始める時刻", "Quiet starts"),
        "Quiet ends" to listOf("免打扰结束小时", "勿擾結束時刻", "通知を控える終了時刻", "Quiet ends"),
        "Importance threshold" to listOf("主动关心重要性阈值", "主動關心重要性門檻", "声かけの重要度しきい値", "Importance threshold"),
        "Humanized delivery" to listOf("短回复节奏", "短回覆節奏", "短い返信のタイミング", "Humanized delivery"),
        "Base delay ms" to listOf("基础延迟（毫秒）", "基礎延遲（毫秒）", "基本遅延（ミリ秒）", "Base delay ms"),
        "Per character ms" to listOf("每字符延迟（毫秒）", "每字元延遲（毫秒）", "1文字あたりの遅延（ミリ秒）", "Per character ms"),
        "Random jitter ms" to listOf("随机浮动（毫秒）", "隨機浮動（毫秒）", "ランダムな変動（ミリ秒）", "Random jitter ms"),
        "Minimum delay ms" to listOf("段间最短延迟（毫秒）", "段間最短延遲（毫秒）", "分割返信の最短間隔（ミリ秒）", "Minimum delay ms"),
        "Maximum delay ms" to listOf("段间最长延迟（毫秒）", "段間最長延遲（毫秒）", "分割返信の最長間隔（ミリ秒）", "Maximum delay ms"),
        "Split probability" to listOf("分段倾向", "分段傾向", "返信を分割する傾向", "Split probability"),
        "Back" to listOf("返回", "返回", "戻る", "Back"),
        "‹ Back" to listOf("‹ 返回", "‹ 返回", "‹ 戻る", "‹ Back"),
        "Companion role" to listOf("AI角色与相处方式", "AI角色與相處方式", "AIの役割と接し方", "Companion role"),
        "Role first" to listOf("先决定我怎样陪伴你", "先決定我怎樣陪伴你", "まず、どんな相手になってほしいか", "Choose how I keep you company"),
        "Role introduction" to listOf("先选择AI扮演怎样的交流伙伴，再了解你是谁。下面的情境是偏好选择，不是心理测评；可随时修改。", "先選擇AI扮演怎樣的交流夥伴，再了解你是誰。下方情境是偏好選擇，不是心理測評；可隨時修改。", "まずAIに望む会話相手を選び、その後であなたについて知っていきます。以下は好みの選択であり心理検査ではありません。後から変更できます。", "Choose the kind of companion you want before describing yourself. These scenarios express preferences, not psychological test scores; you can change them anytime."),
        "Role companion" to listOf("平等、可靠的日常朋友", "平等、可靠的日常朋友", "対等で落ち着いた日常の友人", "An equal, steady everyday friend"),
        "Role listener" to listOf("温柔、先倾听的陪伴者", "溫柔、先傾聽的陪伴者", "まず話を聞く、やさしい相手", "A gentle listener"),
        "Role playful" to listOf("轻松、有分寸的损友", "輕鬆、有分寸的損友", "節度のある気さくな友人", "A lighthearted, considerate friend"),
        "Role coach" to listOf("一起进步、不说教的搭档", "一起進步、不說教的夥伴", "説教せず一緒に成長する仲間", "A collaborative growth partner"),
        "Role custom" to listOf("我自己描述角色", "我自己描述角色", "自分で役割を説明する", "Describe my own character"),
        "AI name" to listOf("角色昵称（选填）", "角色暱稱（選填）", "呼び名（任意）", "Character nickname (optional)"),
        "Character description" to listOf("角色描述：性格、说话方式、相处关系（选填）", "角色描述：性格、說話方式、相處關係（選填）", "性格・話し方・関わり方の説明（任意）", "Character description: personality, tone, relationship (optional)"),
        "Character boundaries" to listOf("角色需要避免的行为（选填）", "角色需要避免的行為（選填）", "この相手に避けてほしい振る舞い（任意）", "Behaviors this character should avoid (optional)"),
        "Role transparency" to listOf("角色是AI的交流设定，不是真人身份；不会要求你依赖它、也不会把角色背景误记成你的身份。", "角色是AI的交流設定，不是真人身分；不會要求你依賴它，也不會把角色背景誤記成你的身分。", "役割はAIの会話設定であり実在の人物ではありません。依存を求めたり、役柄の情報をあなたの情報として記憶したりしません。", "A character is AI conversational framing, not a real person. It must not demand dependency or copy its character background into your identity."),
        "Scenario support" to listOf("你难受时，你更希望它怎样回应？", "你難受時，你更希望它怎樣回應？", "つらい時、どんな返し方をしてほしい？", "When you're upset, what response would help?"),
        "Choice listen" to listOf("先听我说、接住情绪", "先聽我說、接住情緒", "まず聞いて、気持ちを受け止めてほしい", "Listen first and acknowledge my feelings"),
        "Choice solutions" to listOf("听完后一起想办法", "聽完後一起想辦法", "聞いた後で解決策も一緒に考えたい", "Listen, then work on solutions together"),
        "Scenario disagreement" to listOf("它与你意见不同时？", "它與你意見不同時？", "意見が違う時は？", "When it disagrees with you?"),
        "Choice gentle" to listOf("温和说理由，别急着反驳", "溫和說理由，別急著反駁", "やさしく理由を説明してほしい", "Explain gently, without rushing to rebut"),
        "Choice direct" to listOf("可以直接指出不同意见", "可以直接指出不同意見", "違う意見も率直に言ってほしい", "It can disagree directly"),
        "Scenario playfulness" to listOf("平常闲聊能开玩笑吗？", "平常閒聊能開玩笑嗎？", "普段の雑談で冗談は？", "How playful should casual chat be?"),
        "Choice quiet" to listOf("少玩笑，不调侃我", "少玩笑，不調侃我", "冗談は控えめ、からかわないで", "Few jokes, no teasing"),
        "Choice playful" to listOf("可以轻松调侃，但别伤人", "可以輕鬆調侃，但別傷人", "傷つけない範囲なら気軽に冗談を", "Kind humor and gentle teasing are welcome"),
        "Scenario detail" to listOf("普通聊天的回复长度？", "一般聊天的回覆長度？", "普段の返信の長さは？", "Length of everyday replies?"),
        "Choice short" to listOf("短一点，像聊天", "短一點，像聊天", "短く、会話らしく", "Short and conversational"),
        "Choice detailed" to listOf("愿意多听它说一点", "願意多聽它說一點", "もう少し詳しく聞きたい", "A little more detail"),
        "Scenario initiative" to listOf("聊天里谁来带话题？", "聊天裡誰來帶話題？", "話題を広げるのは？", "Who should move the conversation forward?"),
        "Choice wait" to listOf("等我说，少反问", "等我說，少反問", "私が話すのを待ち、質問は少なめに", "Let me lead; fewer follow-up questions"),
        "Choice topics" to listOf("也可以主动带些话题", "也可以主動帶些話題", "相手から話題を出してもよい", "It can introduce topics too"),
        "Scenario closeness" to listOf("相处时的亲近程度？", "相處時的親近程度？", "距離感は？", "How close should the tone feel?"),
        "Choice reserved" to listOf("友好，但保留分寸", "友好，但保留分寸", "親切でも距離感は保ってほしい", "Friendly, with some distance"),
        "Choice warm" to listOf("温暖亲近，但不黏人", "溫暖親近，但不黏人", "温かく親しく、でもべったりせず", "Warm and close, but not clingy"),
        "Not selected" to listOf("未选择：沿用所选角色的起点", "未選擇：沿用所選角色的起點", "未選択：選んだ役割の初期設定を使います", "Not selected: use the chosen role's starting style"),
        "Clear choice" to listOf("清除这项选择", "清除這項選擇", "この選択を解除", "Clear this choice"),
        "Preview label" to listOf("相处方式预览（本地示例，不是模型试跑）", "相處方式預覽（本地範例，不是模型試跑）", "接し方のプレビュー（端末内の例、モデル実行ではありません）", "Style preview (local examples, not a model test)"),
        "Preview listen" to listOf("“先不用急着解决，我听你说。”", "「先不用急著解決，我聽你說。」", "「今すぐ解決しなくていいよ。まず聞かせて。」", "“No need to solve it right away. I'm listening.”"),
        "Preview solutions" to listOf("“先说说卡在哪里，我们一起挑一个小步骤。”", "「先說說卡在哪裡，我們一起挑一個小步驟。」", "「どこで困っているか話して。一緒に小さな一歩を選ぼう。」", "“Tell me where you're stuck; let's pick one small step together.”"),
        "Save role and continue" to listOf("保存角色，再了解我的偏好", "儲存角色，再了解我的偏好", "役割を保存し、私の好みへ", "Save role, then my preferences"),
        "Use default role" to listOf("先用平等朋友，直接开始", "先用平等朋友，直接開始", "対等な友人の初期設定で始める", "Start with the default equal friend"),
        "Language" to listOf("语言", "語言", "言語", "Language"),
        "Language help" to listOf("界面、提示和通知随语言切换；历史原话不翻译。模型默认使用该语言，仍可在聊天中要求其他语言。", "介面、提示與通知隨語言切換；歷史原話不翻譯。模型預設使用該語言，仍可在聊天中要求其他語言。", "画面・案内・通知の言語を切り替えます。過去の原文は翻訳しません。モデルの既定言語も変わり、会話中に別言語を指定できます。", "Changes UI, hints and notifications, not historical quotations. Also sets the default reply language; request another language in chat if needed."),
        "Saved models" to listOf("已保存模型（同一接口）", "已儲存模型（同一介面）", "保存したモデル（同じ接続先）", "Saved models (same endpoint)"),
        "Vision capability" to listOf("此模型支持图像输入（手动标记）", "此模型支援圖像輸入（手動標記）", "画像入力に対応するモデル（手動設定）", "This model accepts images (manually declared)"),
        "Vision help" to listOf("勾选后聊天栏可选图发送，图片只交给当前接口，可能额外计费。能力标记不自动验证模型；不确定请保持关闭。", "勾選後聊天列可選圖傳送，圖片只交給目前介面，可能額外計費。此標記不自動驗證模型；不確定請關閉。", "オンにすると会話で画像を送信できます。現在の接続先にのみ送られ、追加料金がかかる場合があります。対応は自動確認しません。", "Enable to pick and send images in chat to your current provider; extra image fees may apply. This flag does not verify model capability."),
        "Save model entry" to listOf("记住当前模型配置", "記住目前模型設定", "現在のモデル設定を記録", "Remember this model configuration"),
        "Active model {0}" to listOf("当前模型：{0}", "目前模型：{0}", "現在のモデル：{0}", "Active model {0}"),
        "Style section" to listOf("情境偏好（选填，可改）", "情境偏好（選填，可改）", "場面ごとの好み（任意・変更可）", "Scenario preferences (optional, editable)"),
        "Character defaults" to listOf("默认角色不是一张白纸：平等、自然、有分寸。明确反馈可调整风格，不会偷偷更换角色身份。", "預設角色不是一張白紙：平等、自然、有分寸。明確回饋可調整風格，不會偷偷更換角色身分。", "初期の相手は白紙ではなく、対等・自然・節度ある存在です。好みに合わせて話し方を調整しても、役割の身元は勝手に変えません。", "The default is not a blank slate: equal, natural and considerate. Feedback refines style without silently changing the character's identity."),
        "Role save failed" to listOf("角色保存失败，请重试。", "角色儲存失敗，請重試。", "役割を保存できませんでした。再試行してください。", "Couldn't save the role. Please retry."),
        "Background start failed" to listOf("系统未允许启动常驻服务；待办仍保存，可重开应用或选择省电调度。", "系統未允許啟動常駐服務；排程仍已儲存，可重新開啟或選擇省電排程。", "常駐サービスの開始が許可されませんでした。予定は保存済みです。再度開くか省電力モードを選んでください。", "Android didn't allow the resident service to start. Jobs are saved; reopen the app or choose system scheduling."),
        "Resident notification" to listOf("OpenWoven 常驻调度", "OpenWoven 常駐排程", "OpenWoven 常駐スケジュール", "OpenWoven resident scheduling"),
        "Resident notification body" to listOf("等待回复与关心待办；系统休眠时仍可能延后", "等待回覆與關心排程；系統休眠時仍可能延後", "返信・声かけの予定を待機中。端末の休眠で遅れる場合があります。", "Waiting for replies and check-ins; device sleep may still delay delivery"),
        "Stop resident" to listOf("停止常驻", "停止常駐", "常駐を停止", "Stop resident mode"),
        "Notifications description" to listOf("AI回复与主动关心通知", "AI回覆與主動關心通知", "AIからの返信と声かけ", "AI replies and check-ins"),
        "API key or provider access was rejected." to listOf("密钥或模型访问被拒绝。", "金鑰或模型存取遭拒。", "キーまたはモデルへのアクセスが拒否されました。", "API key or provider access was rejected."),
        "The provider is busy or rate-limited. Try again shortly." to listOf("模型服务繁忙或限流，请稍后重试。", "模型服務忙碌或限制頻率，請稍後重試。", "モデルサービスが混雑または利用制限中です。後で再試行してください。", "The provider is busy or rate-limited. Try again shortly."),
        "The request timed out. Your message was saved; you can retry." to listOf("请求超时，消息已保存，可以重试。", "請求逾時，訊息已儲存，可以重試。", "時間切れです。メッセージは保存済みで再試行できます。", "The request timed out. Your message was saved; you can retry."),
        "No network connection. Your message was saved." to listOf("网络不可用，消息已保存。", "網路無法使用，訊息已儲存。", "ネットワークを利用できません。メッセージは保存済みです。", "No network connection. Your message was saved."),
        "Something went wrong. Your chat history is safe." to listOf("操作未完成，请重试；聊天记录仍保留。", "操作未完成，請重試；聊天記錄仍保留。", "操作を完了できませんでした。再試行してください。会話は保存されています。", "Something went wrong. Your chat history is safe."),
        "Connection successful" to listOf("连接成功", "連線成功", "接続成功", "Connection successful"),
        "Connection failed" to listOf("连接失败，请检查地址、密钥和网络。", "連線失敗，請檢查位址、金鑰與網路。", "接続できません。URL・キー・ネットワークを確認してください。", "Connection failed"),
        "Role description companion" to listOf("平等稳重、自然聊天，有自己的观点，不过度追问。", "平等穩重、自然聊天，有自己的觀點，不過度追問。", "対等で落ち着いた相手。自然に話し、自分の意見も持ち、質問攻めにしません。", "Equal and steady, natural conversation with its own views and few follow-up questions."),
        "Role description listener" to listOf("先理解感受，再考虑办法；少说教，不擅自诊断。", "先理解感受，再考慮辦法；少說教，不擅自診斷。", "まず気持ちを理解し、それから解決策へ。説教や勝手な診断はしません。", "Understand feelings before solutions; no unsolicited lecturing or diagnosis."),
        "Role description playful" to listOf("轻松幽默，善意调侃；认真倾诉时收起玩笑。", "輕鬆幽默，善意調侃；認真傾訴時收起玩笑。", "気軽でユーモラス。深刻な相談では冗談を控えます。", "Lighthearted and kindly playful; serious moments override jokes."),
        "Role description coach" to listOf("一起拆解目标和行动，不当上司；你可以拒绝建议。", "一起拆解目標和行動，不當上司；你可以拒絕建議。", "目標や行動を一緒に整理。上司ではなく、助言は断れます。", "Work through goals together, not as a boss; you can decline advice."),
        "Role description custom" to listOf("用下面的描述指定气质、说话习惯和关系定位，不要填写用户资料。", "用下面的描述指定氣質、說話習慣和關係定位，不要填寫使用者資料。", "下の説明に性格・話し方・関係性を書いてください。ユーザーのプロフィールとは別です。", "Describe temperament, speaking habits and relationship—not facts about the user."),
        "Not loaded" to listOf("尚未加载", "尚未載入", "未読み込み", "Not loaded"),
        "Naturalness" to listOf("自然程度", "自然程度", "自然さ", "Naturalness"),
        "Comfort" to listOf("舒适程度", "舒適程度", "心地よさ", "Comfort"),
        "Refresh" to listOf("刷新", "重新整理", "更新", "Refresh"),
        "Search" to listOf("搜索", "搜尋", "検索", "Search"),
        "Previous page" to listOf("上一页", "上一頁", "前のページ", "Previous page"),
        "Next page" to listOf("下一页", "下一頁", "次のページ", "Next page"),
        "Page {0}" to listOf("第 {0} 页", "第 {0} 頁", "{0} ページ", "Page {0}"),
        "Messages {0}" to listOf("{0} 条消息", "{0} 則訊息", "メッセージ {0} 件", "Messages {0}"),
        "Original messages {0}" to listOf("{0} 条原始消息", "{0} 則原始訊息", "元のメッセージ {0} 件", "Original messages {0}"),
        "Excerpt {0}" to listOf("摘录：{0}", "摘錄：{0}", "抜粋：{0}", "Excerpt: {0}"),
        "You" to listOf("你", "你", "あなた", "You"),
        "AI" to listOf("AI", "AI", "AI", "AI"),
        "日期结束后自动归档，原话始终保留。休眠期间未完成的整理会在下次打开时补做。" to listOf("日期结束后自动归档，原话始终保留。休眠期间未完成的整理会在下次打开时补做。", "日期結束後自動歸檔，原話始終保留。休眠時未完成的整理會在下次開啟時補做。", "日付が変わると自動で整理し、原文は残します。休眠中の未処理分は次回起動時に整理します。", "Completed days are archived without deleting original messages. Missed maintenance catches up when reopened."),
        "关键词或日期，例如 2026-07-11" to listOf("关键词或日期，例如 2026-07-11", "關鍵字或日期，例如 2026-07-11", "キーワードまたは日付（例：2026-07-11）", "Keyword or date, e.g. 2026-07-11"),
        "序号月份从首次聊天所在月份起算；月内第 2 周第 3 天指该月 10 日。" to listOf("序号月份从首次聊天所在月份起算；月内第 2 周第 3 天指该月 10 日。", "序號月份從首次聊天所在月份起算；月內第 2 週第 3 天指當月 10 日。", "月の番号は最初の会話の月から数えます。月内の第2週の3日目は10日です。", "Numbered months start with your first chat month. Day 3 of week 2 within a month means its 10th day."),
        "这份归档已被删除或正在重新整理，请返回后刷新。" to listOf("这份归档已被删除或正在重新整理，请返回后刷新。", "這份歸檔已刪除或正在重新整理，請返回後重新整理。", "削除または再整理中です。戻って更新してください。", "This archive was deleted or is being rebuilt. Go back and refresh."),
        "暂时无法读取记忆，请稍后刷新。" to listOf("暂时无法读取记忆，请稍后刷新。", "暫時無法讀取記憶，請稍後重新整理。", "記憶を読み込めません。後で更新してください。", "Couldn't read memory. Please refresh later."),
        "部分消息未完成学习；下面仍可查看原话。" to listOf("部分消息未完成学习；下面仍可查看原话。", "部分訊息未完成學習；下方仍可查看原話。", "一部のメッセージは学習未完了ですが、下で原文を確認できます。", "Some learning is unfinished; original messages are still available below."),
        "原始聊天" to listOf("原始聊天", "原始聊天", "元の会話", "Original conversation"),
        "还没有已结束的归档。今天的聊天明天会出现在这里。" to listOf("还没有已结束的归档。今天的聊天明天会出现在这里。", "尚無已結束的歸檔。今天的聊天明天會出現在這裡。", "完了した期間の記録はまだありません。今日の会話は明日ここに表示されます。", "No completed archives yet. Today's chat will appear here tomorrow."),
        "未找到匹配内容。可以换关键词或直接输入日期；目前不是语义搜索。" to listOf("未找到匹配内容。可以换关键词或直接输入日期；目前不是语义搜索。", "未找到符合內容。可更換關鍵字或輸入日期；目前不是語義搜尋。", "一致する記録がありません。別のキーワードや日付を試してください。意味による検索ではありません。", "No matches. Try another keyword or date; this is not semantic search."),
        "历史记录" to listOf("历史记录", "歷史記錄", "過去の記録", "History"),
        "查看摘要和原话" to listOf("查看摘要和原话", "查看摘要與原話", "要約と原文を見る", "View summary and original messages"),
        "日" to listOf("日", "日", "日", "Day"),
        "周" to listOf("周", "週", "週", "Week"),
        "月" to listOf("月", "月", "月", "Month"),
        "日归档" to listOf("日归档", "日歸檔", "日別記録", "Daily archive"),
        "周归档" to listOf("周归档", "週歸檔", "週別記録", "Weekly archive"),
        "月归档" to listOf("月归档", "月歸檔", "月別記録", "Monthly archive"),
        "先认识一下你" to listOf("补充你的资料（选填）", "補充你的資料（選填）", "あなたの情報（任意）", "Your profile (optional)"),
        "Questionnaire page {0} of {1}" to listOf("第 {0}/{1} 页 · 全部选填", "第 {0}/{1} 頁 · 全部選填", "{0}/{1} ページ・すべて任意", "Page {0} of {1} · all optional"),
        "5个建议问题 · 随时跳过" to listOf("2个建议问题 · 随时跳过", "2 個建議問題 · 隨時跳過", "おすすめの2問・スキップ可", "2 suggested questions · skip anytime"),
        "不需要先填完整份问卷。没回答的偏好保持默认，不会当成你的明确选择；聊天和反馈会继续调整画像。本地保存，不调用AI。" to listOf("角色已经设置好。这里仅补充你的资料，不决定AI身份。未回答不当作明确选择；聊天和反馈会继续完善画像。本地保存，不调用AI。", "角色已設定好。這裡僅補充你的資料，不決定AI身分。未回答不視為明確選擇；聊天與回饋會完善畫像。本地儲存，不呼叫AI。", "役割は設定済みです。ここではあなたの情報だけを補います。未回答は好みと見なさず、会話で更新します。端末保存でAI呼び出しはありません。", "The role is already set. These optional details describe you, not the AI's identity. Unanswered items aren't treated as choices. Saved locally, without AI calls."),
        "主动关心默认每天最多一次，可在设置关闭。" to listOf("主动关心默认每天最多一次，可在设置关闭。", "主動關心預設每日最多一次，可在設定關閉。", "自発的な声かけは初期設定で1日1回まで。設定でオフにできます。", "Check-ins default to at most once a day and can be disabled. "),
        "此版本默认省电调度，后台消息可能延后。" to listOf("当前采用省电调度，后台消息可能延后。", "目前採用省電排程，背景訊息可能延後。", "現在は省電力スケジュールを選択しています。通知が遅れる場合があります。", "System scheduling is selected; background messages may be delayed."),
        "此版本默认带持续通知的常驻模式；可在设置或常驻通知中停止，仍可能被系统限制。" to listOf("此版本默认带持续通知的常驻模式；可在设置或常驻通知中停止，仍可能被系统限制。", "此版本預設持續通知的常駐模式；可在設定或通知中停止，仍可能受系統限制。", "この版は通知付き常駐モードが初期設定です。設定や通知で停止でき、OSの制限も受けます。", "This edition defaults to resident mode with an ongoing notification. Stop it in settings or the notification; Android may still restrict it."),
        "保存并开始聊天" to listOf("保存并开始聊天", "儲存並開始聊天", "保存して会話を始める", "Save and start chatting"),
        "保存并继续" to listOf("保存并继续", "儲存並繼續", "保存して次へ", "Save and continue"),
        "只回答5个建议问题" to listOf("只回答2个建议问题", "只回答2個建議問題", "おすすめの2問だけ", "Only the 2 suggested questions"),
        "展开完整30题" to listOf("展开完整资料（30项选填）", "展開完整資料（30項選填）", "すべての情報を開く（30項・任意）", "Open full profile (30 optional items)"),
        "保存已填内容，直接开始聊天" to listOf("保存已填内容，直接开始聊天", "儲存已填內容，直接開始聊天", "入力済みの内容を保存して会話へ", "Save entered details and start chatting"),
        "尚未选择：保持默认，也可以直接跳过" to listOf("尚未选择：保持角色默认，也可以跳过", "尚未選擇：保留角色預設，也可跳過", "未選択：役割の初期設定を使います。スキップ可", "Not selected: keep character defaults, or skip"),
        "这个程度就好" to listOf("这个程度就好", "這個程度就好", "この程度でよい", "Use this level"),
        "少" to listOf("少", "少", "少ない", "Less"),
        "多" to listOf("多", "多", "多い", "More"),
        "选填，不想回答可以留空" to listOf("选填，不想回答可以留空", "選填，不想回答可留空", "任意。空欄でも構いません", "Optional—leave blank if you prefer"),
        "关于你（选填）" to listOf("关于你（选填）", "關於你（選填）", "あなたについて（任意）", "About you (optional)"),
        "兴趣" to listOf("兴趣", "興趣", "興味", "Interests"),
        "目标" to listOf("目标", "目標", "目標", "Goals"),
        "喜好" to listOf("喜好", "喜好", "好み", "Preferences"),
        "边界" to listOf("边界", "界線", "境界線", "Boundaries"),
        "交流方式" to listOf("交流方式", "交流方式", "話し方", "Conversation style"),
        "No API demo" to listOf("未配置 API 时使用本地示例回复，不是真正的 LLM 对话；保存设置不需要联网。", "未設定 API 時使用本地範例回覆，不是真正的 LLM 對話；儲存設定不需連網。", "API未設定時は端末内のデモ応答です。本物のLLM会話ではありません。保存に通信は不要です。", "Without an API, replies are local examples, not real LLM conversations. Saving settings doesn't require a connection."),
        "Help Semantic Observer" to listOf("默认关闭。开启会额外调用模型提取画像，增加费用；先用本地规则即可。", "預設關閉。開啟會額外呼叫模型提取畫像，增加費用；可先用本地規則。", "初期設定はオフ。オンにすると情報抽出に追加のモデル呼び出しと費用が発生します。", "Off by default. Enabling adds model calls for profile extraction and cost; local rules work without it."),
        "Help Learning enabled" to listOf("默认开启。从聊天与反馈更新画像；关闭后只聊天，保留已学记忆。", "預設開啟。由聊天與回饋更新畫像；關閉後只聊天，保留既有記憶。", "初期設定はオン。会話と評価から更新します。オフでは学習を止め、既存の記憶は残します。", "On by default. Update from chats and feedback. Turning off stops learning, not existing memories."),
        "开场白稍后回复（目标1–3分钟）" to listOf("开场白稍后回复（目标1–3分钟）", "開場白稍後回覆（目標1–3分鐘）", "短い呼びかけへの返信を遅らせる（目安1～3分）", "Greeting delay"),
        "仅独立的‘在吗／有空吗’。正在聊天、求助或含实际问题时不额外等待；可关闭。" to listOf("默认关闭。开启后，独立‘在吗’可多等1–3分钟；继续发实际内容就恢复普通等待。", "預設關閉。開啟後，獨立『在嗎』可多等1–3分鐘；繼續傳實際內容就恢復一般等待。", "初期設定はオフ。短い呼びかけのみ1〜3分遅らせます。内容を続けると通常の待ち時間に戻ります。", "Off by default. Standalone greetings may wait 1–3 minutes; further sent content restores the normal wait."),
        "记忆日历" to listOf("记忆日历", "記憶日曆", "記憶カレンダー", "Memory calendar"),
        "按日、周、月查看；搜索过去的聊天" to listOf("日／周／月归档，查找过去的聊天", "日／週／月歸檔，尋找過去的聊天", "日・週・月の記録と過去の会話検索", "Day/week/month archives and past conversations"),
        "后台运行" to listOf("后台运行", "背景執行", "バックグラウンド動作", "Background"),
        "常驻后台" to listOf("常驻后台", "常駐背景", "常駐モード", "Resident mode"),
        "关闭后使用系统省电调度，可能延后。常驻会显示持续通知、额外耗电，仍可能被系统停止；重开应用会按选择恢复。" to listOf("关闭后使用省电调度。常驻会显示持续通知并额外耗电，仍可能被系统停止，不保证准点。", "關閉後使用省電排程。常駐會顯示持續通知並額外耗電，仍可能被系統停止，不保證準時。", "オフにすると省電力スケジュールを使います。常駐は通知を表示し電力を消費しますが、停止・遅延の可能性は残ります。", "Off uses battery-friendly scheduling. Resident mode shows an ongoing notification and uses more power; Android can still stop or delay it."),
        "Google 推送（FCM）" to listOf("Google推送（FCM）", "Google推播（FCM）", "Googleプッシュ通知（FCM）", "Google push (FCM)"),
        "尚未接入：需要 Firebase 项目和可信服务端，不会自动检测Google服务" to listOf("尚未接入：需要Firebase项目和服务端", "尚未接入：需要Firebase專案與伺服器", "未接続：Firebaseプロジェクトとサーバーが必要", "Not connected: requires a Firebase project and server"),
        "启用可停止的常驻模式？" to listOf("启用可停止的常驻模式？", "啟用可停止的常駐模式？", "停止可能な常駐モードを有効にしますか？", "Enable resident mode?"),
        "应用会显示常驻通知并等待已保存的回复／关心待办。不是防杀保活，也不保证准点。你可以在设置或常驻通知里随时停止。" to listOf("会持续显示通知并等待已保存的待办。不是防杀保活，也不保证准点；设置和通知都能停止。", "會持續顯示通知並等待已儲存的待辦。不是防止系統終止，也不保證準時；設定與通知均可停止。", "保存済みの予定を待ちながら継続通知を表示します。停止防止や定刻実行は保証されません。設定・通知から停止できます。", "Shows an ongoing notification while waiting for saved jobs. Not kill-proof or exact-time delivery; stop it in settings or the notification."),
        "启用" to listOf("启用", "啟用", "有効にする", "Enable"),
        "取消" to listOf("取消", "取消", "キャンセル", "Cancel"),
        "为什么还没有 Google 推送？" to listOf("为什么还没有Google推送？", "為什麼還沒有Google推播？", "Googleプッシュ通知が未接続なのはなぜ？", "Why no Google push yet?"),
        "FCM只负责将服务端消息送到手机。记忆、计时和AI回复还需要在线服务端，并处理设备令牌、认证和数据同步。目前是本地运行版本，没有这些服务，所以先提供省电调度和常驻两种模式。" to listOf("FCM只是投递通道。记忆、计时和AI回复需要服务端、鉴权与同步。当前先提供本地省电／常驻模式，不自动检测Google服务。", "FCM只是投遞通道。記憶、計時與AI回覆需要伺服器、驗證與同步。目前先提供本地省電／常駐模式，不自動偵測Google服務。", "FCMは配送経路です。記憶・予約・AI返信にはサーバー、認証、同期が必要です。現在は端末内の省電力／常駐モードを提供し、Googleサービスの自動検出はしません。", "FCM is a delivery channel. Memory, scheduling and AI replies need a server, authentication and synchronization. This version offers local system/resident modes, without detecting Google services."),
        "明白" to listOf("明白", "了解", "了解", "OK"),
        "稍后回复（后台可能延后）" to listOf("稍后回复（后台可能延后）", "稍後回覆（背景可能延後）", "後ほど返信（バックグラウンドでは遅れる場合があります）", "Waiting reply"),
        "返回" to listOf("返回", "返回", "戻る", "Back"),
        "刷新" to listOf("刷新", "重新整理", "更新", "Refresh"),
        "搜索" to listOf("搜索", "搜尋", "検索", "Search"),
        "清除" to listOf("清空", "清空", "消去", "Clear"),
        "上一页" to listOf("上一页", "上一頁", "前のページ", "Previous page"),
        "下一页" to listOf("下一页", "下一頁", "次のページ", "Next page"),
        "暂时跳过，直接聊天" to listOf("跳过", "略過", "スキップ", "Skip"),
        "清除我的选择" to listOf("清除这项选择", "清除這項選擇", "この選択を解除", "Clear this choice"),
        "Help Temperature" to listOf("默认0.7（0–2）。越低越稳、越高变化越多；先保持0.7。", "預設0.7（0–2）。越低越穩、越高變化越多；先保留0.7。", "初期値0.7（0〜2）。低いほど安定し、高いほど変化が増えます。", "Default 0.7 (0–2). Lower is steadier, higher more varied. Start at 0.7."),
        "Help Top P" to listOf("默认1（0.01–1）。控制候选范围；通常只调温度，不同时改两项。", "預設1（0.01–1）。控制候選範圍；通常只調溫度，不同時改兩項。", "初期値1（0.01〜1）。候補範囲を調整します。温度と同時に変えないのが無難です。", "Default 1 (0.01–1). Candidate sampling range; usually tune temperature instead, not both."),
        "Help Max tokens" to listOf("默认800（96–8192）。单次回复上限，实际按长度偏好缩减；调高可能更贵。", "預設800（96–8192）。單次回覆上限，依長度偏好縮減；調高可能更貴。", "初期値800（96〜8192）。応答上限で、好みにより縮小します。増やすと費用も増え得ます。", "Default 800 (96–8192). Reply ceiling, reduced by length preference. Raising it may increase cost."),
        "Help Timeout seconds" to listOf("默认60秒（5–180）。服务较慢再调高，不会提高模型质量。", "預設60秒（5–180）。服務較慢再調高，不會提升模型品質。", "初期値60秒（5〜180）。遅いサービスなら増やせますが、品質は変わりません。", "Default 60 seconds (5–180). Raise for slower providers, not better answers."),
        "Help Retry" to listOf("默认2次（0–5）。临时失败的重试次数，不含第一次；可能增加等待和费用。", "預設2次（0–5）。暫時失敗的重試次數，不含首次；可能增加等待與費用。", "初期値2回（0〜5）。初回以外の一時的エラーの再試行回数。待ち時間や費用が増え得ます。", "Default 2 (0–5) retries after the first attempt. May add waiting and cost."),
        "Help Context budget" to listOf("默认5400（512–16000），估算输入预算。超出时保留最新连续对话，较早内容留在本地摘要；不是模型精确token硬限。", "預設5400（512–16000），估算輸入預算。超出時保留最新連續對話，較早內容留在本地摘要；非模型精確token硬限。", "初期値5400（512〜16000）。最近の連続した会話を優先し、古い内容は端末内の要約に残します。正確なtoken上限ではありません。", "Default 5400 (512–16000), estimated input budget. Keep a recent contiguous tail; older content stays in local summaries. Not an exact token cap."),
        "Help Summary message threshold" to listOf("默认12（4–100）。累积消息达到阈值触发滚动摘要；较低更频繁，不删除原话。", "預設12（4–100）。累積訊息達門檻觸發滾動摘要；較低更頻繁，不刪原話。", "初期値12（4〜100）。この件数で会話要約を作成。低いほど頻繁で、原文は削除しません。", "Default 12 (4–100). Messages before a rolling summary. Lower means more frequent; originals remain."),
        "Help Summary token threshold" to listOf("默认5400（200–10000）。消息数或估算token任一达到阈值，就本地整理旧内容，保留原文且不额外调用模型。", "預設5400（200–10000）。訊息數或估算token任一達門檻，就本地整理舊內容，保留原文且不額外呼叫模型。", "初期値5400（200〜10000）。件数か概算tokenの上限で端末内の要約を更新します。原文を残し、追加APIは使いません。", "Default 5400 (200–10000) estimated tokens. Either threshold triggers local summaries; originals remain and no extra model call is made."),
        "Help Weak evidence rate" to listOf("默认0.025（0.005–0.08）。从不确定线索缓慢学习，越低越不易误学。", "預設0.025（0.005–0.08）。由不確定線索慢慢學習，越低越不易誤學。", "初期値0.025（0.005〜0.08）。曖昧な手がかりの学習速度。低いほど慎重です。", "Default 0.025 (0.005–0.08). Learning from weak clues; lower is more cautious."),
        "Help Explicit evidence rate" to listOf("默认0.11（0.05–0.25）。明确偏好的学习速度，不是概率。", "預設0.11（0.05–0.25）。明確偏好的學習速度，不是機率。", "初期値0.11（0.05〜0.25）。明示した好みの更新速度で、確率ではありません。", "Default 0.11 (0.05–0.25). Update rate for explicit preferences, not a probability."),
        "Help Correction evidence rate" to listOf("默认0.36（0.15–0.45）。纠正比弱线索更快生效；过高会来回摆动。", "預設0.36（0.15–0.45）。糾正比弱線索更快生效；過高會反覆擺動。", "初期値0.36（0.15〜0.45）。訂正を速く反映。高すぎると好みが揺れます。", "Default 0.36 (0.15–0.45). Corrections take effect faster; too high may cause oscillation."),
        "Help Maximum per day" to listOf("默认1（1–5）。主动关心的每日上限；关闭主动消息可完全停止。", "預設1（1–5）。主動關心每日上限；關閉主動訊息可完全停止。", "初期値1（1〜5）。1日の自発的な声かけ上限。機能をオフにすると停止します。", "Default 1 (1–5) unsolicited check-ins per day. Turn proactive messages off to stop them."),
        "Help Minimum interval hours" to listOf("默认8小时（1–168）。主动关心之间最小间隔，越大越少打扰。", "預設8小時（1–168）。主動關心間最小間隔，越大越少打擾。", "初期値8時間（1〜168）。自発的な声かけの間隔。長いほど控えめです。", "Default 8 hours (1–168) between check-ins. Higher is less intrusive."),
        "Help Quiet starts" to listOf("默认22点（0–23），使用设备当地时间。开始=结束代表全天不限制。", "預設22點（0–23），使用裝置當地時間。開始=結束代表不限制。", "初期値22時（0〜23）、端末の現地時間。開始と終了が同じなら制限なしです。", "Default 22 (0–23), device local time. Equal start/end means no quiet interval."),
        "Help Quiet ends" to listOf("默认8点（0–23），跨午夜有效；提醒可能顺延到免打扰结束。", "預設8點（0–23），可跨午夜；提醒可能順延至免打擾結束。", "初期値8時（0〜23）。日付を跨げます。通知が終了時刻まで延びることがあります。", "Default 8 (0–23). Overnight intervals work; reminders may move to quiet-hours end."),
        "Help Importance threshold" to listOf("默认0.68（0–1）。主动关心的启发式门槛，越高越克制，不是成功概率。", "預設0.68（0–1）。主動關心的啟發式門檻，越高越克制，非成功機率。", "初期値0.68（0〜1）。自発的な声かけの判定基準。高いほど控えめで、成功率ではありません。", "Default 0.68 (0–1), heuristic check-in threshold. Higher is more selective, not a success probability."),
        "Help Base delay ms" to listOf("默认750毫秒（0–2000）。分条间隔的基础等待，另加字数和随机变化。首条额外等待最多900毫秒，扣除模型耗时；不含开场白分钟级延迟。", "預設750毫秒（0–2000）。分條間隔的基本等待，另加字數和隨機變化。首條額外等待最多900毫秒，扣除模型耗時；不含開場白分鐘級延遲。", "初期値750ms（0〜2000）。吹き出し間隔の基本値に文字数と揺らぎを加算。最初は最大900msから生成時間を差し引きます。挨拶の待機は別です。", "Default 750 ms (0–2000), plus character count and jitter between bubbles. First-bubble waiting is capped at 900 ms minus generation time; greeting waits are separate."),
        "Help Per character ms" to listOf("默认30毫秒（0–50）。下一条越长，间隔越长；短句约1秒，40字左右约2秒。", "預設30毫秒（0–50）。下一條越長，間隔越長；短句約1秒，40字左右約2秒。", "初期値30ms（0〜50）。次の文が長いほど間隔が長くなります。短文は約1秒、40文字なら約2秒です。", "Default 30 ms (0–50) per character of the next bubble: about 1 second for short messages, 2 for 40 characters."),
        "Help Random jitter ms" to listOf("默认150毫秒（0–2000）。展示间隔的随机变化，不代表真人正在打字。", "預設150毫秒（0–2000）。顯示間隔的隨機變化，不代表真人打字。", "初期値150ms（0〜2000）。表示間隔のランダム変化。人間が入力中という意味ではありません。", "Default 150 ms (0–2000) random display variation, not real human typing."),
        "Help Minimum delay ms" to listOf("默认800毫秒（0–2000）。第二条及后续气泡间隔下限，不额外拖慢首条。", "預設800毫秒（0–2000）。第二條及後續氣泡間隔下限，不額外拖慢首條。", "初期値800ms（0〜2000）。2つ目以降の間隔の下限。最初の表示は遅らせません。", "Default 800 ms (0–2000), minimum gap for the second and subsequent bubbles, not the first."),
        "Help Maximum delay ms" to listOf("默认2500毫秒（不低于下限，最多5000）。限制每条展示间隔，不限制网络生成耗时或输入暂停。", "預設2500毫秒（不低於下限，最多5000）。限制每條顯示間隔，不限制網路生成耗時或輸入暫停。", "初期値2500ms（下限以上、最大5000）。各表示間隔の上限。通信時間や入力待ちは別です。", "Default 2500 ms (minimum delay to 5000), per-bubble gap cap. Network latency and pauses for your typing are separate."),
        "Help Split probability" to listOf("默认0.32（0–1），控制其他回复的随机分段。日常中文按自然断句稳定拆分，不依赖概率；关闭自然节奏仍保留独立气泡，但不等待。不增加模型调用。", "預設0.32（0–1），控制其他回覆的隨機分段。日常中文依自然斷句穩定拆分，不依賴機率；關閉自然節奏仍保留獨立氣泡，但不等待。不增加模型呼叫。", "初期値0.32（0〜1）。中国語の日常会話は自然な区切りで分割し、それ以外にこの確率を使います。間隔をオフにしても吹き出しは別々で、即時表示。追加APIなし。", "Default 0.32 (0–1) for other reply splitting. Casual Chinese uses natural boundaries. Turning timing off keeps separate bubbles but removes waits. No extra model calls."),
        "Preference reply_length" to listOf("回复长度", "回覆長度", "返信の長さ", "Reply length"),
        "Preference warmth" to listOf("温暖程度", "溫暖程度", "温かさ", "Warmth"),
        "Preference humor" to listOf("幽默程度", "幽默程度", "ユーモア", "Humor"),
        "Preference teasing" to listOf("调侃程度", "調侃程度", "冗談の程度", "Teasing"),
        "Preference directness" to listOf("直接程度", "直接程度", "率直さ", "Directness"),
        "Preference empathy" to listOf("共情程度", "共情程度", "共感", "Empathy"),
        "Preference question_frequency" to listOf("追问频率", "追問頻率", "質問の頻度", "Question frequency"),
        "Preference initiative" to listOf("话题主动性", "話題主動性", "話題の積極性", "Initiative"),
        "Preference advice_frequency" to listOf("建议频率", "建議頻率", "助言の頻度", "Advice frequency"),
        "Preference emoji_frequency" to listOf("表情频率", "表情頻率", "絵文字の頻度", "Emoji frequency"),
        "Data raw" to listOf("原始消息", "原始訊息", "元のメッセージ", "Raw messages"),
        "Data evidence" to listOf("学习证据", "學習證據", "学習の根拠", "Evidence"),
        "Data metrics" to listOf("用量记录", "用量記錄", "利用量", "Usage metrics"),
        "Data rolling" to listOf("滚动摘要", "滾動摘要", "会話要約", "Rolling summaries"),
        "Data daily" to listOf("每日", "每日", "日別", "Daily"),
        "Data weekly" to listOf("每周", "每週", "週別", "Weekly"),
        "Data monthly" to listOf("每月", "每月", "月別", "Monthly"),
        "Data long_term" to listOf("长期记忆", "長期記憶", "長期記憶", "Long-term memory"),
        "Data policy" to listOf("本轮策略", "本輪策略", "今回の方針", "Turn policy"),
        "Data audit" to listOf("审计记录", "稽核記錄", "監査記録", "Audit log"),
        "Status pending" to listOf("待发送", "待傳送", "送信待ち", "Pending"),
        "Status sent" to listOf("已发送", "已傳送", "送信済み", "Sent"),
        "Status cancelled" to listOf("已取消", "已取消", "キャンセル済み", "Cancelled"),
        "Status expired" to listOf("已过期", "已過期", "期限切れ", "Expired"),
        "Question q01" to listOf("你希望我怎么称呼你？昵称就可以。", "你希望我怎麼稱呼你？暱稱即可。", "どう呼べばいいですか？ニックネームで構いません。", "What should I call you? A nickname is fine."),
        "Question q02" to listOf("愿意的话，说说你的年龄段；不需要生日或证件信息。", "願意的話，說說年齡層；不需生日或證件資訊。", "よければ年代を教えてください。誕生日や身分証の情報は不要です。", "If you want, share your age range—no birthday or ID details needed."),
        "Question q03" to listOf("你通常在哪个城市或地区生活？不需要详细地址。", "你通常住在哪個城市或地區？不需詳細地址。", "普段暮らす都市や地域は？詳しい住所は不要です。", "Which city or region do you usually live in? No exact address."),
        "Question q04" to listOf("你目前在怎样的学习环境里？不用提供真实校名。", "目前在怎樣的學習環境？不需真實校名。", "今はどんな環境で学んでいますか？実際の学校名は不要です。", "What is your learning environment like? No real school name needed."),
        "Question q05" to listOf("你正在学什么专业或科目？", "你正在學什麼專業或科目？", "何を専攻・勉強していますか？", "What subjects or major are you studying?"),
        "Question q06" to listOf("你平时做哪一类工作或活动？", "你平時做哪類工作或活動？", "普段はどんな仕事や活動をしていますか？", "What kind of work or activities do you usually do?"),
        "Question q07" to listOf("最近你对哪些事最感兴趣？", "最近對哪些事情最有興趣？", "最近、何に一番興味がありますか？", "What interests you most lately?"),
        "Question q08" to listOf("哪些活动会让你真心开心？", "哪些活動讓你真心開心？", "心から楽しいと感じる活動は？", "Which activities genuinely make you happy?"),
        "Question q09" to listOf("有哪些事让你明显不喜欢？", "有哪些事情讓你明顯不喜歡？", "特に苦手なことや嫌いなことは？", "What do you strongly dislike?"),
        "Question q10" to listOf("你有哪些重要的习惯或固定安排？", "有哪些重要習慣或固定安排？", "大事な習慣や決まった予定は？", "What important habits or routines do you have?"),
        "Question q11" to listOf("你目前最想完成什么？", "你目前最想完成什麼？", "今、最も達成したいことは？", "What would you most like to accomplish now?"),
        "Question q12" to listOf("长期来看，你想做到什么或过怎样的生活？", "長期來看，想做到什麼或過怎樣的生活？", "長い目で見て、何を成し遂げ、どんな生活をしたいですか？", "Long term, what would you like to achieve or how would you like to live?"),
        "Question q13" to listOf("有哪些话题，你愿意经常和我聊？", "有哪些話題願意經常和我聊？", "よく一緒に話したい話題は？", "What topics would you like us to discuss often?"),
        "Question q14" to listOf("你喜欢哪些书、游戏、电影、动漫或节目？", "你喜歡哪些書、遊戲、電影、動漫或節目？", "好きな本・ゲーム・映画・アニメ・番組は？", "What books, games, films, anime or shows do you like?"),
        "Question q15" to listOf("你喜欢什么音乐或歌手？", "你喜歡什麼音樂或歌手？", "好きな音楽や歌手は？", "What music or singers do you like?"),
        "Question q16" to listOf("你喜欢哪些食物或饮料？", "你喜歡哪些食物或飲料？", "好きな食べ物や飲み物は？", "What foods or drinks do you like?"),
        "Question q17" to listOf("哪些价值观或原则对你比较重要？", "哪些價值觀或原則對你重要？", "大事にしている価値観や原則は？", "Which values or principles matter to you?"),
        "Question q18" to listOf("聊到什么，会让你更舒服或觉得被理解？", "聊到什麼讓你更舒服或感到被理解？", "どんな話なら心地よく、理解してもらえたと感じますか？", "What topics help you feel comfortable or understood?"),
        "Question q19" to listOf("有哪些话题、称呼或说话方式，你不希望我使用？", "有哪些話題、稱呼或說話方式你不希望我使用？", "避けてほしい話題・呼び方・話し方は？", "What topics, names or speaking styles should I avoid?"),
        "Question q20" to listOf("你的日常作息，还有什么希望我记住？", "關於日常作息，還有什麼希望我記住？", "日常の生活リズムについて、覚えてほしいことは？", "Anything else about your routine you'd like me to remember?"),
        "Question q21" to listOf("回复更喜欢简短还是详细？少＝简短，多＝详细。", "回覆喜歡簡短或詳細？少＝簡短，多＝詳細。", "返信は短めと詳しめ、どちらが好み？少＝短め、多＝詳しめ。", "Do you prefer brief or detailed replies? Less = brief, more = detailed."),
        "Question q22" to listOf("希望交流有多温暖、亲近？", "希望交流多溫暖、親近？", "どれくらい温かく親しい話し方がいいですか？", "How warm and close should our conversations feel?"),
        "Question q23" to listOf("喜欢多大程度的幽默？", "喜歡多少幽默？", "ユーモアはどれくらい好みですか？", "How much humor do you prefer?"),
        "Question q24" to listOf("能接受多少善意的调侃？", "能接受多少善意調侃？", "軽い冗談はどれくらい平気ですか？", "How much kind teasing are you comfortable with?"),
        "Question q25" to listOf("希望说话有多直接？", "希望說話多直接？", "どれくらい率直な話し方がいいですか？", "How direct should I be?"),
        "Question q26" to listOf("希望多大程度地回应情绪？", "希望多大程度回應情緒？", "気持ちにどれくらい寄り添ってほしいですか？", "How much emotional acknowledgment would you like?"),
        "Question q27" to listOf("希望多常追问？少＝少反问，多＝多了解。", "希望多常追問？少＝少反問，多＝多了解。", "質問の頻度は？少＝控えめ、多＝もっと知る。", "How often should I ask follow-ups? Less = fewer questions."),
        "Question q28" to listOf("希望多主动带动话题？", "希望多主動帶動話題？", "どれくらい話題を持ち出してほしいですか？", "How often should I introduce conversation topics?"),
        "Question q29" to listOf("倾诉时希望多常给建议？少＝先听，多＝一起想办法。", "傾訴時希望多常給建議？少＝先聽，多＝一起想辦法。", "相談時の助言の頻度は？少＝まず聞く、多＝一緒に考える。", "How often should I offer advice? Less = listen first, more = solve together."),
        "Question q30" to listOf("喜欢多常使用表情？", "喜歡多常使用表情？", "絵文字はどれくらい使ってほしいですか？", "How often should I use emoji?"),
        "Help Base URL" to listOf("默认 https://api.openai.com/v1。填服务商兼容接口的根地址，不要重复添加 /chat/completions。", "預設 https://api.openai.com/v1。填服務商相容接口根位址，不要重複加 /chat/completions。", "初期値 https://api.openai.com/v1。互換APIのベースURLを入力し、/chat/completions は付けません。", "Default https://api.openai.com/v1. Use the provider's compatible base URL, without /chat/completions."),
        "Help API key" to listOf("可留空，不会自动申请。配置后，测试、聊天、手动角色生成及开启的主动消息会使用接口，可能产生费用。", "可留空，不會自動申請。設定後，測試、聊天、手動角色生成及啟用的主動訊息會使用介面，可能產生費用。", "空欄可。自動発行しません。設定後の接続テスト・会話・手動の役柄生成・有効な声かけはAPIを使い、料金が発生する場合があります。", "May be blank; no automatic key creation. Tests, chat, manual character generation and enabled proactive messages can use the configured provider and incur costs."),
        "Help Dialogue model" to listOf("默认 gpt-4.1-mini，仅为占位配置。填服务商实际支持的名称；这里切换当前聊天模型，不会自动下载模型。", "預設 gpt-4.1-mini，僅為佔位設定。填服務商實際支援名稱；此處切換目前聊天模型，不自動下載。", "初期値 gpt-4.1-mini は設定例です。提供元が対応する名前を入力してください。端末にモデルをダウンロードしません。", "Default gpt-4.1-mini is a placeholder configuration. Enter a supported provider model name; no model is downloaded."),
        "Help Observer model" to listOf("默认 gpt-4.1-mini。仅开启语义观察且配置API时使用；可选便宜模型，但提取不一定准确。", "預設 gpt-4.1-mini。僅開啟語義觀察且設定API時使用；便宜模型的提取未必準確。", "初期値 gpt-4.1-mini。意味ベースの観察をオンにし、APIを設定した場合だけ使用します。", "Default gpt-4.1-mini. Used only with semantic observation enabled and an API configured. Cheaper extraction may be less accurate."),
        "Preference help" to listOf("0代表更少，1代表更多，是交流风格刻度，不是心理测评分数。未学习的起点来自角色草案；问卷明确数值、手动修改与明确反馈优先于推测。", "0代表較少，1代表較多，是交流風格刻度，非心理測評分數。未學習的起點來自角色草案；問卷明確數值、手動修改與明確回饋優先於推測。", "0は少なく、1は多く。会話スタイルの目安で心理テストではありません。役柄の案が初期値で、明示した数値・好みを推測より優先します。", "0 means less and 1 more: style controls, not psychological scores. The character draft supplies unlearned starting values; explicit answers and feedback outrank inference."),
        "Base URL and API key are required" to listOf("请先填写接口地址和密钥；可以留空使用离线示例。", "請先填寫接口位址與金鑰；可留空使用離線範例。", "接続にはURLとキーが必要です。空欄ならオフラインデモを使えます。", "Base URL and API key are required; leave them blank to use the offline demo."),
        "Boundaries" to listOf("角色边界", "角色界線", "役柄の境界", "Character boundaries"),
        "Interview edit answers" to listOf("从前置题开始修改", "從前置題開始修改", "最初の質問から編集", "Edit from the first questions"),
        "Updating chat history" to listOf("正在更新聊天记录…", "正在更新聊天記錄…", "会話履歴を更新しています…", "Updating chat history…"),
        "Interview title" to listOf("建立陪伴者", "建立陪伴者", "相手のキャラクターをつくる", "Build your companion"),
        "Interview introduction" to listOf("前置10题：5题了解你，5题建立角色。关键词即可，也可选“暂不确定”。完整版50题，两边各25题。", "前置10題：5題了解你，5題建立角色。關鍵詞即可，也可選「暫不確定」。完整版50題，兩邊各25題。", "最初の10問：あなたについて5問、相手について5問。キーワードや「まだ未定」で大丈夫です。全50問では各25問になります。", "Start with 10 questions: 5 about you and 5 about the character. Keywords or “Not sure yet” are enough. The full interview has 25 of each."),
        "Interview base character" to listOf("自然说话，有自己的观点，记住共同话题。昵称和背景接好模型后再生成，也可以自己选择。", "自然說話，有自己的觀點，記住共同話題。暱稱和背景接好模型後再生成，也可自己選擇。", "自然に話し、自分の意見と共通の話題を持つ相手に。呼び名や背景はモデル接続後に生成するか、自分で選べます。", "Natural speech, independent views and shared continuity. Generate a nickname and backstory after model setup, or choose your own."),
        "Interview user section" to listOf("关于你", "關於你", "あなたについて", "About you"),
        "Interview character section" to listOf("希望它是什么样", "希望它是什麼樣", "どんな相手がいいか", "Your desired companion"),
        "Interview keyword hint" to listOf("几个关键词或短例子即可", "幾個關鍵詞或短例子即可", "キーワードや短い例で大丈夫", "Keywords or a short example"),
        "Interview unsure" to listOf("暂不确定", "暫不確定", "まだ未定", "Not sure yet"),
        "Interview required hint" to listOf("请回答或选择“暂不确定”，不必提供真实身份信息。", "請回答或選「暫不確定」，不必提供真實身分資料。", "回答するか「まだ未定」を選んでください。本名などは不要です。", "Answer or choose “Not sure yet”. Real identity details are not needed."),
        "Interview selected level" to listOf("已选择的程度", "已選擇的程度", "選択した度合い", "Selected level"),
        "Interview untouched slider" to listOf("此刻度尚未保存为答案。调整后确认，或选择暂不确定。", "此刻度尚未儲存為答案。調整後確認，或選暫不確定。", "この値は未回答です。調整して確認するか未定を選べます。", "This slider is unanswered. Adjust and confirm, or choose not sure."),
        "Interview choice female" to listOf("女性角色", "女性角色", "女性キャラクター", "Female character"),
        "Interview choice male" to listOf("男性角色", "男性角色", "男性キャラクター", "Male character"),
        "Interview choice neutral" to listOf("不指定性别", "不指定性別", "性別指定なし", "No gender preference"),
        "Interview choice listen" to listOf("先倾听", "先傾聽", "まず聞く", "Listen first"),
        "Interview choice solutions" to listOf("一起想办法", "一起想辦法", "一緒に考える", "Solve together"),
        "Interview choice mixed" to listOf("先理解，再想办法", "先理解，再想辦法", "理解してから考える", "Understand, then solve"),
        "Interview page {0} of {1}" to listOf("第{0}页 / 共{1}页", "第{0}頁 / 共{1}頁", "{0} / {1} ページ", "Page {0} of {1}"),
        "Interview first five user" to listOf("前5题：你是什么样的人", "前5題：你是什麼樣的人", "最初の5問：あなたについて", "First 5: who you are"),
        "Interview first five character" to listOf("后5题：它应该是什么样的角色", "後5題：它應該是什麼樣的角色", "次の5問：どんな相手がいいか", "Next 5: who your companion should be"),
        "Interview extra user" to listOf("补充了解你（20题）", "補充了解你（20題）", "あなたについての追加20問", "20 more about you"),
        "Interview extra character" to listOf("补充角色与交流方式（20题）", "補充角色與交流方式（20題）", "性格・会話スタイルの追加20問", "20 more about character and conversation"),
        "Interview save next" to listOf("保存并继续", "儲存並繼續", "保存して次へ", "Save and continue"),
        "Interview use answered" to listOf("用已回答内容生成草案", "用已回答內容產生草案", "回答済みの内容で案をつくる", "Build from answered questions"),
        "Interview draft title" to listOf("角色草案与昵称", "角色草案與暱稱", "キャラクター案と呼び名", "Character draft and nickname"),
        "Interview draft notice" to listOf("先保存你的角色偏好，不在离线时猜定人物。接好接口后可回来生成昵称和简介。", "先儲存角色偏好，不在離線時猜定人物。接好介面後可回來生成暱稱與簡介。", "まず希望を保存します。オフラインで人物像を決めつけず、接続後に呼び名や紹介を生成できます。", "Save your preferences first. Offline setup doesn't decide the character; return after provider setup to generate a name and profile."),
        "Interview automatic name" to listOf("留空先用临时称呼，接模型后生成", "留空先用暫時稱呼，接模型後生成", "空欄なら仮の呼び名。接続後に生成できます", "Blank uses a temporary name until model generation"),
        "Interview generate nickname" to listOf("使用推荐昵称", "使用推薦暱稱", "おすすめの呼び名を使う", "Use suggested nickname"),
        "Interview generation prompt" to listOf("查看角色生成提示词", "查看角色生成提示詞", "役柄生成のプロンプトを見る", "View character generation prompt"),
        "Interview continue fifty" to listOf("继续完整版50题", "繼續完整版50題", "全50問を続ける", "Continue the full 50"),
        "Interview confirm start" to listOf("确认角色，开始聊天", "確認角色，開始聊天", "確認して会話を始める", "Confirm and start chatting"),
        "Interview gradual adaptation" to listOf("昵称和基本角色不会因普通聊天随意重写；表达方式根据明确反馈逐渐调整。以后可回来补充或修改答案。", "暱稱與基本角色不因普通聊天隨意重寫；表達方式依明確回饋逐漸調整。以後可補充或修改答案。", "普段の会話で呼び名や基本の役柄を勝手に変えません。明示した好みに合わせて話し方を少しずつ調整します。回答は後で変更できます。", "Ordinary chat will not randomly rewrite the name or core character. Explicit feedback gradually adjusts conversation style. Answers can be updated later."),
        "Question q31" to listOf("最近最投入的学习、工作或项目是什么？", "最近最投入的學習、工作或專案是什麼？", "最近力を入れている勉強・仕事・プロジェクトは？", "What study, work or project are you focused on?"),
        "Question q32" to listOf("哪些情况容易让你有压力？", "哪些情況容易讓你有壓力？", "どんな状況でストレスを感じますか？", "What situations tend to stress you out?"),
        "Question q33" to listOf("心情低落时通常怎样恢复？", "心情低落時通常怎樣恢復？", "落ち込んだときどう回復しますか？", "How do you recover when feeling low?"),
        "Question q34" to listOf("相处时最看重哪些原则？", "相處時最看重哪些原則？", "人との関係で大切にしていることは？", "What principles matter most in a relationship?"),
        "Question q35" to listOf("有什么话题希望以后继续聊？", "有什麼話題希望以後繼續聊？", "今後も話したい話題は？", "What should we keep talking about later?"),
        "Question q36" to listOf("希望它给你什么感觉？如温柔、活泼、沉稳、有主见。", "希望它給你什麼感覺？如溫柔、活潑、沉穩、有主見。", "どんな雰囲気がいいですか？優しい、明るい、落ち着いた、自分の考えがある、など。", "What should it feel like? Gentle, lively, calm or independently minded?"),
        "Question q37" to listOf("角色是女性、男性，还是不指定？自定义身份可填在角色介绍中", "角色是女性、男性，還是不指定？自訂身分可填在角色介紹中", "女性、男性、それとも指定なし？独自の設定は役柄の紹介に記入できます", "Female, male, or unspecified? Describe custom identity in the character profile"),
        "Question q38" to listOf("希望怎样相处？朋友、亲近的搭档、一起学习的人，或其他？", "希望怎樣相處？朋友、親近搭檔、一起學習的人，或其他？", "友達、親しい相棒、勉強仲間、または別の関係？", "Friends, close partners, study companions or something else?"),
        "Question q39" to listOf("说“今天很累”时，希望先倾听、一起想办法，还是两者兼顾？", "說「今天很累」時，希望先傾聽、一起想辦法，還是兩者兼顧？", "「今日は疲れた」と言ったら、聞いてほしい、一緒に考えたい、それとも両方？", "When you say “I'm tired today”, should it listen, help solve things or both?"),
        "Question q40" to listOf("哪些表现绝对不要？如说教、黏人、挖苦、总是顺着你。", "哪些表現絕對不要？如說教、黏人、挖苦、總是順著你。", "避けてほしいことは？説教、しつこさ、嫌味、何でも同意すること、など。", "What should it avoid: lecturing, clinginess, sarcasm or always agreeing?"),
        "Question q41" to listOf("希望它叫什么？没有想法可以自动取名。", "希望它叫什麼？沒想法可自動取名。", "どんな呼び名がいいですか？未定なら候補を選べます。", "What nickname should it have? Automatic suggestions are available."),
        "Question q42" to listOf("希望它有哪些稳定的性格特点？", "希望有哪些穩定性格？", "どんな安定した性格がいいですか？", "What lasting personality traits should it have?"),
        "Question q43" to listOf("希望角色有哪些兴趣，想一起聊哪些领域？", "希望角色有哪些興趣，想一起聊哪些領域？", "相手の趣味や、一緒に話したい分野は？", "What interests should the character have, and what would you explore together?"),
        "Question q44" to listOf("意见不同时喜欢怎样表达和解释？", "意見不同時喜歡怎樣表達解釋？", "意見が違うときの伝え方は？", "How should it express disagreement?"),
        "Question q45" to listOf("哪些玩笑舒服，哪些不要开？", "哪些玩笑舒服，哪些不要開？", "好きな冗談と避けたい冗談は？", "What jokes feel good and which are off limits?"),
        "Question q46" to listOf("喜欢怎样的称呼、口头禅或措辞？", "喜歡怎樣的稱呼、口頭禪或措辭？", "呼び方や言葉遣いの好みは？", "Any preferred forms of address, phrases or wording?"),
        "Question q47" to listOf("成功或失落时希望分别怎么回应？", "成功或失落時希望分別怎麼回應？", "成功と落胆のときの反応は？", "How should it respond to successes and disappointments?"),
        "Question q48" to listOf("忙或暂时不回消息时如何保持分寸？", "忙或暫時不回訊息時如何保持分寸？", "忙しいときや返信しないときの距離感は？", "How should it respect your space when busy or not replying?"),
        "Question q49" to listOf("如何支持成长，而不是替你决定？", "如何支持成長，而不是替你決定？", "代わりに決めずどう成長を支えてほしいですか？", "How should it support growth without deciding for you?"),
        "Question q50" to listOf("举个特别喜欢或讨厌的回应的短例子。", "舉個特別喜歡或討厭回應的短例子。", "好き、または嫌いな返答の短い例は？", "Give a short example of a response you like or dislike."),
        "Character awaiting model" to listOf("待接模型后生成昵称与人物", "待接模型後生成暱稱與人物", "接続後に呼び名と人物像を生成", "Name and character pending model setup"),
        "Generate character with model" to listOf("一次提炼画像并生成角色", "一次提煉画像並產生角色", "1回でプロフィール整理と役柄生成", "Distill profile and generate character together"),
        "Character generation cost" to listOf("发送问卷答案与角色约束，点击后调用模型，失败可能按设置重试并计费；确认才保存。", "傳送問卷答案與角色約束，點擊後呼叫模型，失敗可能依設定重試並計費；確認才儲存。", "回答と役柄の条件を送ります。押すとAPIを使い、設定に応じた再試行も課金される場合があります。確認後に保存します。", "Sends answers and character instructions. Clicking uses the model; configured retries may also cost money. Save only after review."),
        "Connect model for character" to listOf("还没配置接口：先保存进入聊天，再到接口设置填写模型，回来生成。", "尚未設定介面：先儲存進入聊天，到介面設定填模型後再回來生成。", "未接続です。まず保存して会話へ進み、接続先を設定してから戻れます。", "No provider configured. Save and enter chat, configure your provider, then return to generate."),
        "Interview model draft notice" to listOf("当前模型生成的角色建议。可以改昵称或选候选；确认前不会替换原角色。", "目前模型生成的角色建議。可改暱稱或選候選；確認前不替換原角色。", "モデルからの提案です。呼び名を編集・選択できます。確認するまで現在の役柄は変わりません。", "A model-generated proposal. Edit or select a name; it won't replace the current character until confirmed."),
        "Interview saved model notice" to listOf("已保存的模型角色；只补资料不会自动重写人物。需要时可重新生成。", "已儲存的模型角色；只補資料不會自動重寫人物。需要時可重新生成。", "保存済みの役柄です。プロフィールの追加だけで書き換えません。必要なら再生成できます。", "Your saved character. Adding profile details won't rewrite it automatically; regenerate when you choose."),
        "Character generation failed" to listOf("角色生成失败，原草案仍保留。请检查接口、输出额度或稍后重试。", "角色生成失敗，原草案仍保留。請檢查介面、輸出額度或稍後重試。", "生成できませんでした。元の案は保持されています。接続や出力上限を確認して再試行してください。", "Generation failed; the previous draft is kept. Check the provider/output limit or retry later."),
        "Suggested fictional details" to listOf("待确认的虚构背景与兴趣", "待確認的虛構背景與興趣", "提案された架空の背景・趣味", "Suggested fictional backstory and interests"),
        "Slider left {0}" to listOf("0：{0}", "0：{0}", "0：{0}", "0: {0}"),
        "Slider right {0}" to listOf("1：{0}", "1：{0}", "1：{0}", "1: {0}"),
        "Slider value {0}" to listOf("当前值：{0} / 1", "目前值：{0} / 1", "現在値：{0} / 1", "Current: {0} / 1"),
        "Slider short" to listOf("简短", "簡短", "短く", "Brief"),
        "Slider detailed" to listOf("详细", "詳細", "詳しく", "Detailed"),
        "Slider reserved" to listOf("克制", "克制", "控えめ", "Reserved"),
        "Slider warm" to listOf("亲切", "親切", "親しみやすく", "Warm"),
        "Slider serious" to listOf("认真", "認真", "真面目", "Serious"),
        "Slider humorous" to listOf("幽默", "幽默", "ユーモラス", "Humorous"),
        "Slider no teasing" to listOf("不打趣", "不打趣", "からかわない", "No teasing"),
        "Slider gentle teasing" to listOf("轻松打趣", "輕鬆打趣", "軽く冗談を言う", "Gentle teasing"),
        "Slider tactful" to listOf("委婉", "委婉", "やわらかく", "Tactful"),
        "Slider direct" to listOf("直接", "直接", "率直", "Direct"),
        "Slider rational" to listOf("偏理性", "偏理性", "理性的", "More rational"),
        "Slider empathetic" to listOf("重共情", "重共情", "共感を重視", "More empathetic"),
        "Slider few questions" to listOf("少追问", "少追問", "質問を控える", "Fewer follow-ups"),
        "Slider more questions" to listOf("多追问", "多追問", "詳しく聞く", "More follow-ups"),
        "Slider wait for me" to listOf("等我开口", "等我開口", "こちらが話すまで待つ", "Wait for me"),
        "Slider start topics" to listOf("主动找话题", "主動找話題", "話題を持ち出す", "Start topics"),
        "Slider listen first" to listOf("先倾听", "先傾聽", "まず聞く", "Listen first"),
        "Slider more advice" to listOf("多给建议", "多給建議", "助言を増やす", "More advice"),
        "Slider no emoji" to listOf("不用表情", "不用表情", "絵文字なし", "No emoji"),
        "Slider frequent emoji" to listOf("常用表情", "常用表情", "絵文字をよく使う", "Frequent emoji"),
        "System notification settings" to listOf("系统通知设置", "系統通知設定", "システム通知設定", "System notification settings"),
        "Notifications allowed" to listOf("已允许", "已允許", "許可済み", "Allowed"),
        "Notifications blocked" to listOf("系统尚未允许，点此开启", "系統尚未允許，點此開啟", "未許可。タップして設定", "Blocked by system; tap to enable"),
        "Notification permission hint" to listOf("允许通知后，后台消息才能提醒你；可在系统设置随时关闭。", "允許通知後，背景訊息才能提醒你；可在系統設定隨時關閉。", "通知を許可すると背景のメッセージを受け取れます。システム設定でいつでもオフにできます。", "Allow notifications to receive background message alerts. You can turn them off in system settings."),
        "Enable notifications" to listOf("允许通知", "允許通知", "通知を許可", "Enable notifications"),
        "Notification settings unavailable" to listOf("无法打开系统通知设置，请在手机设置里手动开启。", "無法開啟系統通知設定，請在手機設定裡手動開啟。", "通知設定を開けません。端末の設定から許可してください。", "Cannot open notification settings; enable them in your device settings."),
        "Version and privacy" to listOf("版本与隐私", "版本與隱私", "バージョンとプライバシー", "Version and privacy"),
        "Distilled user profile" to listOf("提炼后的用户要点（确认后写入AUL）", "提煉後的使用者要點（確認後寫入AUL）", "整理したユーザー情報（確認後AULへ保存）", "Distilled user notes (saved to AUL on confirmation)"),
        "Scheduled messages" to listOf("定时消息", "定時訊息", "予約メッセージ", "Scheduled messages"),
        "Schedule messages help" to listOf("指定内容或话题、时间，查看并取消待发送消息", "指定內容或話題、時間，查看並取消待傳送訊息", "内容・話題・時刻を選び、予約の確認と取消", "Choose content/topic and time; view or cancel pending messages"),
        "Schedule app scope" to listOf("消息会发到本应用聊天页，后台通过系统通知提醒；不代发微信、QQ或WhatsApp。", "訊息會發到本應用聊天頁，背景透過系統通知提醒；不代發微信、QQ或WhatsApp。", "このアプリの会話に届き、背景では通知します。他のメッセージアプリへの送信ではありません。", "Messages arrive in this app's chat with background notifications, not in WeChat, QQ or WhatsApp."),
        "Schedule exact text" to listOf("指定内容", "指定內容", "指定した文章", "Exact content"),
        "Schedule model topic" to listOf("到时生成话题", "到時產生話題", "時刻に話題を生成", "Generate at due time"),
        "Schedule text help" to listOf("到时发送你填的原文，不调用模型。", "到時傳送填寫的原文，不呼叫模型。", "指定時刻に入力した文章を送ります。APIは使いません。", "Sends the text you enter at the due time; no model call."),
        "Schedule topic help" to listOf("只保存话题，到时用当前模型生成短消息，可能计费。", "只儲存話題，到時用目前模型產生短訊息，可能計費。", "話題だけを保存し、時刻に現在のモデルで短い会話を生成します。課金される場合があります。", "Stores a topic; the current model generates a short message at the due time and may incur costs."),
        "Schedule no model" to listOf("还没配置模型，可先定时发送指定内容。", "尚未設定模型，可先定時傳送指定內容。", "未接続です。指定文章の予約は使えます。", "No model configured; exact-content scheduling still works."),
        "Schedule topic" to listOf("到时聊什么", "到時聊什麼", "その時の話題", "Topic for later"),
        "Schedule content" to listOf("到时发送的内容", "到時傳送的內容", "送る文章", "Content to send"),
        "Schedule local time" to listOf("按手机本地时间发送", "依手機本地時間傳送", "端末の現地時刻", "Device local time"),
        "Schedule in ten minutes" to listOf("10分钟后", "10分鐘後", "10分後", "In 10 minutes"),
        "Schedule in one hour" to listOf("1小时后", "1小時後", "1時間後", "In one hour"),
        "Schedule tomorrow" to listOf("明天此时", "明天此時", "明日の今頃", "Tomorrow"),
        "Schedule timing help" to listOf("定时是目标时间，省电、断网或系统限制可能延后。免打扰内的时间会顺延；超过24小时有效窗口不再发送。手动预约不占每天自动关心额度。", "定時是目標時間，省電、斷網或系統限制可能延後。免打擾內的時間會順延；超過24小時有效窗口不再傳送。手動預約不占每日自動關心額度。", "予約は目標時刻です。省電力・通信・OSで遅れる場合があります。静かな時間帯は後へ移動し、24時間の有効期間後は送りません。手動予約は自動声かけの上限と別です。", "A target time, not an exact alarm. Power/network/OS limits may delay it. Quiet hours shift it later; it expires after 24 hours. Manual schedules don't use automatic check-in limits."),
        "Schedule save" to listOf("保存定时消息", "儲存定時訊息", "予約を保存", "Save scheduled message"),
        "Schedule saved for {0}" to listOf("已安排：{0}", "已安排：{0}", "予約しました：{0}", "Scheduled for {0}"),
        "Schedule saved outside quiet hours {0}" to listOf("已避开免打扰，安排在：{0}", "已避開免打擾，安排於：{0}", "静かな時間帯を避けて予約：{0}", "Shifted outside quiet hours to {0}"),
        "Schedule future time required" to listOf("请选择未来一年内的时间。", "請選擇未來一年內的時間。", "今から1年以内の未来の時刻を選んでください。", "Choose a future time within one year."),
        "Schedule create failed" to listOf("未能保存预约，请检查时间、内容或模型配置。", "未能儲存預約，請檢查時間、內容或模型設定。", "予約できませんでした。時刻・文章・モデル設定を確認してください。", "Could not save. Check time, content and model configuration."),
        "Schedule load failed" to listOf("未能加载预约，可点击刷新重试。", "未能載入預約，可點選重新整理重試。", "予約を読み込めません。更新して再試行してください。", "Could not load schedules; refresh to retry."),
        "Schedule cancel failed" to listOf("取消失败，请刷新后重试。", "取消失敗，請重新整理後重試。", "取消できません。更新して再試行してください。", "Could not cancel; refresh and retry."),
        "Schedule queue" to listOf("已保存的消息", "已儲存的訊息", "保存した予約", "Saved messages"),
        "Schedule empty" to listOf("还没有定时消息。", "還沒有定時訊息。", "予約はありません。", "No scheduled messages yet."),
        "Schedule automatic followup" to listOf("自动话题或事件跟进", "自動話題或事件跟進", "自動の話題・予定のフォロー", "Automatic topic or event follow-up"),
        "Schedule status pending" to listOf("等待发送", "等待傳送", "送信待ち", "Pending"),
        "Schedule status sent" to listOf("已写入聊天", "已寫入聊天", "チャットに保存済み", "Saved in chat"),
        "Schedule notification pending" to listOf("通知待提交：请检查免打扰、通知权限和消息渠道；超过24小时不补发。", "通知待提交：請檢查免打擾、通知權限與訊息管道；超過24小時不補發。", "通知待ち：静かな時間帯・権限・通知チャンネルを確認してください。24時間後は再送しません。", "Notification pending: check quiet hours, permission and the message channel; no replay after 24 hours."),
        "Schedule notification submitted" to listOf("通知已提交系统，不代表已读。", "通知已提交系統，不代表已讀。", "通知をOSへ送信済み。既読ではありません。", "Notification submitted to Android; not a read receipt."),
        "Schedule notification foreground" to listOf("前台接收，不弹系统通知。", "前景接收，不顯示系統通知。", "アプリ表示中のため通知は出しません。", "Received in foreground; no system notification."),
        "Schedule notification disabled" to listOf("应用通知已关闭，未提交通知。", "應用程式通知已關閉，未提交通知。", "アプリ内の通知設定がオフのため通知しません。", "App notifications were disabled; not submitted."),
        "Schedule notification expired" to listOf("通知补发窗口已过期，聊天记录保留。", "通知補發期限已過，保留聊天記錄。", "通知の再送期限が切れました。チャットは残ります。", "Notification replay expired; chat history is kept."),
        "Schedule status cancelled" to listOf("已取消", "已取消", "取消済み", "Cancelled"),
        "Schedule status expired" to listOf("已过期，不再发送", "已過期，不再傳送", "期限切れ・送信しません", "Expired; won't send"),
        "Schedule cancel" to listOf("取消发送", "取消傳送", "送信を取消", "Cancel delivery"),
    )
    fun text(language: String, key: String, vararg args: Any?): String {
        val index = languages.indexOf(language).coerceAtLeast(0)
        var value = catalog[key]?.get(index) ?: key
        args.forEachIndexed { i, arg -> value = value.replace("{" + i + "}", arg.toString()) }
        return value
    }
    fun language(context: Context): String =
        context.getSharedPreferences("app_language", Context.MODE_PRIVATE).getString("code", "zh-CN") ?: "zh-CN"
}

@Composable
fun tr(key: String, vararg args: Any?): String = UiStrings.text(LocalUiLanguage.current, key, *args)

@Composable
fun LanguagePicker(selected: String, onSelect: (String) -> Unit) {
    androidx.compose.foundation.layout.FlowRow {
        UiStrings.languages.forEachIndexed { index, code ->
            androidx.compose.material3.FilterChip(
                selected = selected == code, onClick = { onSelect(code) },
                label = { androidx.compose.material3.Text(UiStrings.labels[index]) },
            )
        }
    }
}
